Repository DEPthes/4th-MVP-LearningCrew-Web, pull requests merged in 2025-08, with the labels that each got.

#8 feat: creategroup ui 작업
  package-lock.json
  package.json
  src/Router.tsx
  src/assets/ArrowDown.svg
  src/assets/CameraImg.svg
  src/assets/CategoryData.ts
  src/assets/CreateGroupDownArrow.svg
  src/assets/HighArrow.svg
  src/assets/leftArrow.svg
  src/assets/rightArrow.svg
  src/components/.gitignore
  src/components/common/Calendar.tsx
  src/components/common/Input.tsx
  src/components/createGroup/Button.tsx
  src/components/createGroup/Category.tsx
  src/components/createGroup/Container.tsx
  src/components/createGroup/SelectRange.tsx
  src/components/createGroup/UploadImg.tsx
  src/hooks/.gitignore
  src/hooks/createGroupSchema.ts
  src/pages/createGroup/CreateGroup.tsx
  src/pages/shareNote/ShareNoteList.tsx
  src/styles/common/CalendarComponentStyle.module.css
  src/styles/common/InputComponentStyle.module.css
  src/styles/createGroup/Button.module.css
  src/styles/createGroup/CategoryComponentStyle.module.css
  src/styles/createGroup/ContainerComponentStyle.module.css
  src/styles/createGroup/CreateGroupPageStyle.module.css
  src/styles/createGroup/SelectRangeComponentStyle.module.css
  src/styles/createGroup/UploadImgComponentStyle.module.css
Labels: ✨Feat

#7 feat: 네비게이션 바, footer 구현 (#6)
  src/components/common/Footer.tsx
  src/components/common/Navbar.tsx
  src/components/layout/Layout.tsx
  src/styles/components/common/Footer.module.css
  src/styles/components/common/Navbar.module.css
  src/styles/pages/home/HomePageStyle.module.css
Labels: ✨Feat

#23 feat: api 연결
  .gitignore
  package-lock.json
  package.json
  src/apis/.gitignore
  src/apis/login/login.ts
  src/pages/home/Home.tsx
  vite.config.ts
Labels: 🛜api

#18 내그룹_주최그룹_ui
  package-lock.json
  package.json
  src/Router.tsx
  src/components/hostGroupApplicant/ApplicantList.tsx
  src/components/hostGroupApplicant/HostGroupApplicant.tsx
  src/components/hostGroupParticipants/HostGroupParticipants.tsx
  src/components/hostGroupParticipants/ParticipantList.tsx
  src/components/hostGroupStudy/HostGroupStudy.tsx
  src/components/hostGroupStudyWriting/HostGroupStudyWriting.tsx
  src/components/myGroupStudy/MyGroupStudy.tsx
  src/components/signUp/Date.tsx
  src/components/signUp/Gender.tsx
  src/components/signUp/IdInputGroup.tsx
  src/components/signUp/PasswordInputGroup.tsx
  src/components/signUp/Profile.tsx
  src/pages/signUp/SignUp.tsx
  src/styles/hostGroupApplicant/ApplicantList.module.css
  src/styles/hostGroupApplicant/HostGroupApplicant.module.css
  src/styles/hostGroupParticipants/HostGroupParticipants.module.css
  src/styles/hostGroupParticipants/ParticipantList.module.css
  src/styles/hostGroupStudy/HostGroupStudy.module.css
  src/styles/hostGroupStudyWriting/HostGroupStudyWriting.module.css
  src/styles/login/Login.module.css
  src/styles/myGroupStudy/MyGroupStudy.module.css
  src/styles/signUp/Date.module.css
Labels: ✨Feat

#25 feat: 마이페이지 UI 구현
  package-lock.json
  src/Router.tsx
  src/assets/profile.svg
  src/assets/sample.png
  src/components/common/GroupCard.tsx
  src/components/common/GroupTitle.tsx
  src/pages/myPage/EditProfile.tsx
  src/pages/myPage/FavoriteGroupList.tsx
  src/pages/myPage/MyPage.tsx
  src/styles/common/GroupCard.module.css
  src/styles/common/GroupTitle.module.css
  src/styles/myPage/EditProfile.module.css
  src/styles/myPage/FavoriteGroupList.module.css
  src/styles/myPage/MyPage.module.css
  src/styles/pages/myPage/MyPageStyle.module.css
Labels: ✨Feat

#38 Feat/#35 login sign up api
  src/Router.tsx
  src/components/login/Login.tsx
  src/components/signUp/BirthCalendar.tsx
  src/components/signUp/Gender.tsx
  src/components/signUp/IdInputGroup.tsx
  src/components/signUp/PasswordInputGroup.tsx
  src/components/signUp/Profile.tsx
  src/components/welcomePage/WelcomePage.tsx
  src/pages/myPage/EditProfile.tsx
  src/pages/signUp/SignUp.tsx
  src/styles/login/Login.module.css
  src/styles/signUp/BirthCalendar.module.css
  src/styles/signUp/IdInputGroup.module.css
  src/styles/signUp/PasswordInputGroup.module.css
  src/styles/signUp/Profile.module.css
Labels: 🛜api

#39 feat: 홈페이지 UI 구현
  public/icons/all-off.svg
  public/icons/all-on.svg
  public/icons/art-off.svg
  public/icons/art-on.svg
  public/icons/biz-off.svg
  public/icons/biz-on.svg
  public/icons/dev-off.svg
  public/icons/dev-on.svg
  public/icons/exam-off.svg
  public/icons/exam-on.svg
  public/icons/game-off.svg
  public/icons/game-on.svg
  public/icons/hardware-off.svg
  public/icons/hardware-on.svg
  public/icons/job-off.svg
  public/icons/job-on.svg
  public/icons/lang-off.svg
  public/icons/lang-on.svg
  public/icons/sec-off.svg
  public/icons/sec-on.svg
  src/assets/banner.svg
  src/components/common/GroupCard.tsx
  src/components/common/GroupListPage.tsx
  src/components/common/GroupTitle.tsx
  src/components/common/Navbar.tsx
  src/components/common/SearchBar.tsx
  src/components/home/CategoryTabs.tsx
  src/pages/home/Home.tsx
  src/styles/common/GroupListPage.module.css
  src/styles/home/CategoryTabs.module.css
  src/styles/home/Home.module.css
Labels: ✨Feat

#41 Feat: create group api
  src/apis/creatGroup/createGroup.ts
  src/components/createGroup/Button.tsx
  src/components/createGroup/Category.tsx
  src/hooks/createGroupSchema.ts
  src/pages/createGroup/CreateGroup.tsx
Labels: 🛜api

#48 Fix: ui fix
  src/Router.tsx
  src/components/common/Pagenation.tsx
  src/components/common/Sort.tsx
  src/components/createGroup/UploadImg.tsx
  src/components/fixedGroupHeader/ParticipantMenu.tsx
  src/components/layout/GroupLayout.module.css
  src/styles/QandA/WriteBtnComponentStyle.module.css
  src/styles/common/Editor.module.css
  src/styles/common/Font.module.css
  src/styles/common/Navbar.module.css
  src/styles/common/Pagenation.module.css
  src/styles/fixedGroupHeader/ParticipantMenu.module.css
  src/styles/myPage/MyPage.module.css
Labels: 🐞Bug, 💄Design

#49 Feat: qanda 작성 api 연동
  src/Router.tsx
  src/apis/qanda/QandA.ts
  src/components/QandA/WriteBtn.tsx
  src/components/common/ContentEditor.tsx
  src/components/fixedGroupHeader/ParticipantMenu.tsx
  src/components/layout/GroupLayout.module.css
  src/components/layout/GroupLayout.tsx
  src/pages/QandA/QandAList.tsx
  src/pages/QandA/QandAWrite.tsx
  src/pages/myNote/MyNote.tsx
  src/pages/shareNote/ShareNoteList.tsx
  src/styles/QandA/QandAWrite.module.css
  src/styles/QandA/WriteBtnComponentStyle.module.css
  src/styles/common/Editor.module.css
  src/styles/myNote/MyNoteWritePageStyle.module.css
Labels: 🐞Bug, 🛜api

#57 Feat: qna, mynote, sharenote api 연결
  src/Router.tsx
  src/apis/common/File.ts
  src/apis/qanda/QandA.ts
  src/apis/studygroup/Note.ts
  src/apis/studygroup/QandA.ts
  src/apis/studygroup/StudyGroup.ts
  src/components/QandA/Comment.tsx
  src/components/QandA/CommentInput.tsx
  src/components/QandA/CommentList.tsx
  src/components/QandA/WriteBtn.tsx
  src/components/common/Footer.tsx
  src/components/common/List.tsx
  src/components/common/Lock.tsx
  src/components/common/PostDetail.tsx
  src/components/fixedGroupHeader/ParticipantMenu.tsx
  src/components/layout/Layout.tsx
  src/index.css
  src/pages/QandA/QandADetail.tsx
  src/pages/QandA/QandAList.tsx
  src/pages/QandA/QandAWrite.tsx
  src/pages/myNote/MyNote.tsx
  src/pages/myNote/MyNoteWrite.tsx
  src/pages/quiz/Quiz.tsx
  src/pages/quiz/QuizQ.tsx
  src/pages/shareNote/ShareNoteDetail.tsx
  src/pages/shareNote/ShareNoteList.tsx
  src/styles/QandA/Comment.module.css
  src/styles/common/Footer.module.css
  src/styles/common/Lock.module.css
  src/styles/common/PostDetail.module.css
  src/styles/fixedGroupHeader/FixedBanner.module.css
  src/styles/myNote/MyNotePageStyle.module.css
Labels: 🛜api

#65 feat: 홈 api 연동
  src/Router.tsx
  src/apis/common/File.ts
  src/apis/common/studyGroups.ts
  src/components/common/GroupCard.tsx
  src/components/common/GroupListPage.tsx
  src/components/myGroupStudy/MyGroupStudy.tsx
  src/constants/categoryNameToId.ts
  src/pages/home/Home.tsx
  src/utils/mapSort.ts
Labels: 🛜api

#68 fix: QA 사항 수정
  src/styles/myGroup/CreateGroupButton.module.css
  src/styles/myPage/MyPage.module.css
Labels: ♻️Refactor

#72 Feat: 내그룹탭 api 연결
  src/apis/auth/auth.ts
  src/apis/common/File.ts
  src/apis/common/token.ts
  src/apis/creatGroup/createGroup.ts
  src/apis/home/GroupList.ts
  src/apis/studygroup/Note.ts
  src/apis/studygroup/QandA.ts
  src/apis/studygroup/Quiz.ts
  src/apis/studygroup/StudyGroup.ts
  src/assets/DefaultGroup.svg
  src/components/QandA/Comment.tsx
  src/components/QandA/CommentList.tsx
  src/components/common/ContentEditor.tsx
  src/components/common/GroupCard.tsx
  src/components/common/GroupListPage.tsx
  src/components/fixedGroupHeader/Step.tsx
  src/pages/home/Home.tsx
  src/pages/myGroup/MyGroup.tsx
  src/styles/common/GroupCard.module.css
  src/styles/fixedGroupHeader/ParticipantMenu.module.css
  src/types/group.ts
Labels: 🛜api

#74 Fix: mygroup detailgroup UI api fix
  src/App.tsx
  src/apis/home/GroupList.ts
  src/apis/studygroup/Quiz.ts
  src/components/common/GroupListPage.tsx
  src/components/common/Sort.tsx
  src/components/fixedGroupHeader/ParticipantMenu.tsx
  src/components/fixedGroupHeader/Step.tsx
  src/components/myGroupStudy/MyGroupStudy.tsx
  src/hooks/GroupTabContext.tsx
  src/pages/QandA/QandADetail.tsx
  src/pages/QandA/QandAList.tsx
  src/pages/QandA/QandAWrite.tsx
  src/pages/myGroup/MyGroup.tsx
  src/pages/myNote/MyNote.tsx
  src/pages/myNote/MyNoteWrite.tsx
  src/pages/quiz/Quiz.tsx
  src/pages/shareNote/ShareNoteDetail.tsx
  src/pages/shareNote/ShareNoteList.tsx
  src/styles/common/CurrentTabDisplay.module.css
  src/styles/common/GroupListPage.module.css
Labels: 🐞Bug, 💄Design

#77 feat: mypage api 연동
  src/apis/common/File.ts
  src/apis/mypage/users.ts
  src/pages/myPage/EditProfile.tsx
  src/pages/myPage/MyPage.tsx
Labels: 🛜api

#79 feat: 검색, 프로필
  public/default-profile.svg
  src/apis/auth/auth.ts
  src/apis/common/studyGroups.ts
  src/components/common/Navbar.tsx
  src/pages/home/Home.tsx
  src/pages/myGroup/MyGroup.tsx
  src/pages/myPage/FavoriteGroupList.tsx
  src/styles/common/Navbar.module.css
  src/utils/mapSort.ts
Labels: ✨Feat, 🛜api

#81 Fix: groupdetail member api
  src/App.tsx
  src/apis/Group/Members.ts
  src/apis/common/Bookmark.ts
  src/components/common/GroupCard.tsx
  src/components/common/GroupListPage.tsx
  src/components/common/Navbar.tsx
  src/components/common/SearchBar.tsx
  src/components/myGroup/GroupTypesTabs.tsx
  src/hooks/SearchKeywordContext.tsx
  src/pages/myGroup/MyGroup.tsx
  src/styles/common/GroupCard.module.css
Labels: 🐞Bug, 🛜api

#84 Network/#78 search profile
  public/icons/art-off.svg
  public/icons/game-off.svg
  src/apis/auth/auth.ts
  src/apis/common/client.ts
  src/components/common/Navbar.tsx
  src/components/signUp/Profile.tsx
  src/pages/home/Home.tsx
  src/pages/myPage/EditProfile.tsx
  src/pages/myPage/MyPage.tsx
  src/styles/home/CategoryTabs.module.css
  src/styles/myPage/MyPage.module.css
  src/styles/signUp/Profile.module.css
Labels: 🐞Bug, 💄Design, 🛜api

#87 feat: 홈, 마이페이지 (#80)
  src/apis/auth/auth.ts
  src/apis/common/client.ts
  src/apis/common/studyGroups.ts
  src/apis/common/token.ts
  src/components/common/Navbar.tsx
  src/pages/home/Home.tsx
  src/pages/myPage/FavoriteGroupList.tsx
  src/pages/myPage/MyPage.tsx
  src/styles/common/GroupListPage.module.css
  src/styles/home/CategoryTabs.module.css
  src/styles/myPage/MyPage.module.css
  src/utils/mapSort.ts
Labels: ✨Feat, 💄Design, 🛜api

#100 fix: QA 사항
  src/assets/default-profile.svg
  src/components/common/SearchBar.tsx
  src/components/signUp/IdInputGroup.tsx
  src/pages/myPage/EditProfile.tsx
  src/pages/myPage/MyPage.tsx
  src/styles/myPage/MyPage.module.css
Labels: ♻️Refactor

#103 Fix 스터디 작성 api 연결
  src/apis/Group/StudyGroupStep.ts
  src/apis/common/studyGroups.ts
  src/apis/home/GroupList.ts
  src/components/common/ContentEditor.tsx
  src/components/fixedGroupHeader/ParticipantMenu.tsx
  src/components/fixedGroupHeader/Step.tsx
  src/components/hostGroupStudy/HostGroupStudy.tsx
  src/components/hostGroupStudyWriting/HostGroupStudyWriting.tsx
  src/components/myGroupStudy/MyGroupStudy.tsx
  src/pages/home/Home.tsx
  src/pages/myGroup/MyGroup.tsx
  src/styles/fixedGroupHeader/FixedBanner.module.css
  src/styles/hostGroupStudy/HostGroupStudy.module.css
  src/styles/myGroupStudy/MyGroupStudy.module.css
Labels: 🐞Bug

#106 fix: QA 마지막 수정
  src/components/common/Calendar.tsx
  src/components/common/Navbar.tsx
  src/components/header/Header.tsx
  src/styles/QandA/Comment.module.css
  src/styles/common/PostDetail.module.css
  src/styles/fixedGroupHeader/FixedBanner.module.css
  src/styles/hostGroupStudy/HostGroupStudy.module.css
  src/styles/myGroupStudy/MyGroupStudy.module.css
  src/styles/myNote/MyNotePageStyle.module.css
  src/styles/quiz/QuizQPageStyle.module.css
Labels: 🐞Bug
